# Generated by Django 4.1.2 on 2022-11-02 17:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
